
function init()
    
    m.top.setFocus(true)
    m.myLabel = m.top.findNode("myLabel")
    
    'Set the font size
    m.myLabel.font.size = 92
    m.myLabel.text = Doggy.giveMeThecopy("Dani")

    'Set the color to light blue
    m.myLabel.color="0xFFD0EE"
end function

namespace Doggy
    function giveMeThecopy(name as string) as object
        name = name = "" ? "man" : name
        return `Hello ${name}, keep rocking!`
    end function
end namespace